### ISSUE TITLE
Initial connection takes long. Is this a jdbc issue?

### ISSUE THREAD

**Issue by nohelia-merino** [databricks/databricks-sql-python#156]

**Comment by susodapop** [comment]
Hi there, `databricks-sql-connector` doesn't use JDBC. There's not enough information in your report for it to be actionable.

1. What version of `databricks-sql-connector` do you use?
2. How long does the connection take?
3. What region are you running in?
4. Which cloud?

**Comment by nohelia-merino** [comment]
What version of databricks-sql-connector do you use? We use the databricks-sql-connector~=2.5.2 version
How long does the connection take? It takes more than 5 minutes the first time we connect to Databricks.
What region are you running in? us-west-2
Which cloud? The databricks workspace we connect uses AWS cloud storage.

**Comment by nohelia-merino** [comment]
It is my mistake, I meant Thrift Client rather than JDBC, but since both send request to Thrift server, is this a Thrift server issue.

**Comment by susodapop** [comment]
Thank you for your information. This seems like a workspace configuration issue rather than a problem with the connector, unless you see something in the logs indicating otherwise. We'll debug this with you privately (I've been contacted by our support team about this). I'll reopen this issue if we find that it could be relevant to other users or a bug in the connector code.

Thanks!
