### ISSUE TITLE
Make SQLAlchemy an optional dependency

### ISSUE THREAD

**Issue by alonme** [databricks/databricks-sql-python#224]
I am trying to reduce the size of my image, and i noticed that i have SQLA and Alembic installed when i don't really use them,
they take about 14MB together.

WDYT about making these 2 optional dependencies? 
Are you open for a contribution for this issue?

**Comment by susodapop** [comment]
This is a good idea and it's on our radar for the version 3 release coming by the end of next month. We want to reduce the overall package size for a litany of reasons. A PR doing so prematurely would break things for anyone using SQLAlchemy today, however, so it's not something we'll do until shortly before the v3 release.

The end goal would be to configure our pyproject.toml so that users can `pip install databricks-sql-connector[sqlalchemy]` to get a copy with the dialect dependencies included.

**Comment by alonme** [comment]
This seems to be solved by https://github.com/databricks/databricks-sql-python/pull/264

**Comment by susodapop** [comment]
Yep, you can close this issue.
