### ISSUE TITLE
cursor.execute / parameter injection

### ISSUE THREAD

**Issue by cil22** [databricks/databricks-sql-python#239]
Hello,

there is an example file showing an INSERT INTO via cursor.execute and concatenation the values via f string.
https://github.com/databricks/databricks-sql-python/blob/main/examples/insert_data.py
```
    squares = [(i, i * i) for i in range(100)]
    values = ",".join([f"({x}, {y})" for (x, y) in squares])

    cursor.execute(f"INSERT INTO squares VALUES {values}")
```

Is this supposed to be the future method?

Is it currently possible to pass the values with the parameters argument? If so, how would that look like (for multiple simultaneous records to be added)? cursor.executemany(...)?

I would expect less vulnerability to SQL injection and the benefit of automatic type conversion from that functionality.

**Comment by susodapop** [comment]
This is a good catch. Concatenation is risky and we should update the example to demonstrate proper insertion semantics using parameters. That API has been supported since the first version of this connector since it implements PEP-249. It looks like this:

```python
        sql = "INSERT INTO squares VALUES (%(x)s, %(y)s)"
        params = {"x": "10", "y": "12"}
        result = cursor.execute(sql, parameters=params)
```

Note that until DBR 14.1, server-side parameterisation was not possible in Databricks. So using `cursor.execute(statement: str, parameters)` _works_ but can't fully guarantee type safety. Instead the connector locally escapes and sanitises parameter value inputs.

Now that DBR >=14.1 supports parameterisation, we're adding it to this connector as well as part of the forthcoming `3.0.0` release. There have a been a few pull requests implementing this in this past couple weeks but it has not been released yet.

I'm self-assigning this issue so we can update our example.

**Comment by cil22** [comment]
Thanks Jesse.
Just to make sure:
- Would I need to pass all parameters as strings? So no automatic type conversion (Python<->DB)? I'm thinking about strings, integers, float, date / datetime values...
- To insert multiple records at once, would I have to concatenate the VALUES part one my own (for the n records to insert) and pass a list of dictionaries as parameters (params)?

**Comment by susodapop** [comment]
> Would I need to pass all parameters as strings? So no automatic type conversion (Python<->DB)? I'm thinking about strings, integers, float, date / datetime values...

See the edit to my comment above. You the user don't need to convert your values to strings. But under the legacy parameter behaviour (before server-side parameterisation was possible), the connector would coerce all values to strings. This makes sense because queries are always passed to a database as a string. So if you wrote this code:

```python
        sql = "INSERT INTO employees VALUES (%(employee_id)s, %(hire_date)s)"
        # observe the parameter values are Python types
        params = {"employee_id": 24601, "y": datetime.date(1997,10,12)}
        result = cursor.execute(sql, parameters=params)
```

...the string passed to the database would be

```sql
INSERT INTO employees VALUES (24601, '1997-10-12')
```

> To insert multiple records at once, would I have to concatenate the VALUES part one my own (for the n records to insert) and pass a list of dictionaries as parameters (params)?

You can call `cursor.executemany(sql,parameters: List[Dict])` but it's currently not efficient at all. It emit one statement per group of parameters. So if you did this:

```python
        sql = "INSERT INTO employees VALUES (%(employee_id)s, %(hire_date)s)"
        # observe the parameter values are Python types
        params = [
            {"employee_id": 24601, "y": datetime.date(1997,10,12)},
            {"employee_id": 24602, "y": datetime.date(1997,5,21)} 
        ]
        result = cursor.executemany(sql, parameters=params)
```

The connector would emit these statements:

```sql
INSERT INTO employees VALUES (24601, '1997-10-12')
INSERT INTO employees VALUES (24602, '1997-05-21')
```

It would **not** implement this more efficient query:

```sql
INSERT INTO employees VALUES ((24601, '1997-10-12'), (24602, '1997-05-21'))
```

So for the most efficient insert approach, you would need to construct your own SQL string and bind a one-dimensional array of values, like this:

```python
        sql = "INSERT INTO employees VALUES ((%(p1)s, %(p2)s), (%(p3)s, %(p4)s))"
        # observe the parameter values are Python types
        params = {"p1": 24601, "p2": datetime.date(1997,10,12), "p3": 24602, "p4": datetime.date(1997,5,21)}
        result = cursor.execute(sql, parameters=params)
```

**Comment by cil22** [comment]
Thanks for your elaborate explanation!

I tried the suggested approach and unfortunately receive an error:
`databricks.sql.exc.ServerOperationError: Cannot write to table due to mismatched user specified column size(3) and data column size(2).; line 1 pos 70`

```
sql = "insert into test_tbl (col1,col2,col3) values ((%(p0)s,%(p1)s,%(p2)s),(%(p3)s,%(p4)s,%(p5)s))"
params = {'p0': 1, 'p1': 'string1', 'p2': datetime.datetime(2019, 12, 20, 9, 36, 15), 'p3': 2, 'p4': 'string2', 'p5': datetime.datetime(2019, 12, 20, 10, 1, 44)}
```

When trying to insert a single row, `cursor.execute` works. However, multiple records fail. Is there something I'm missing regarding the arrangement of columns/records?

**Comment by susodapop** [comment]
There's not enough info in your message to say for sure. But the error
message suggests you're trying to insert a value into a table with an
incompatible type. Can you share the CREATE TABLE query you used for your
demo?

**Comment by cil22** [comment]
```
CREATE TABLE test_tbl (
  col1 INT,
  col2 STRING,
  col3 TIMESTAMP
)
```
If I try to insert only p0, p1, p2, the statement works...

**Comment by susodapop** [comment]
Thanks for confirming that this approach works. I goofed the syntax in my example.

I think we'll incorporate this discussion into some public place in this repository (the wiki perhaps?) so that others can find it more easily. It will become important for anyone doing ingestion with the connector.
