### ISSUE TITLE
Support `SPARK_CONNECT_USER_AGENT` environment variable

### ISSUE THREAD

**Issue by blairj09** [databricks/databricks-sql-python#301]
There are several existing tools that use the environment variable `SPARK_CONNECT_USER_AGENT` to supply user agent details:
* [`pyspark`](https://github.com/apache/spark/blob/7db85642600b1e3b39ca11e41d4e3e0bf1c8962b/python/pyspark/sql/connect/client/core.py#L288)
* [Databricks VSCode Extension](https://github.com/databricks/databricks-vscode/issues/854)
* [`odbc` R package](https://github.com/r-dbi/odbc/blob/b55664b5e34e6611482e00493c97e98cb19b842a/R/databricks.R#L178)
* [`pysparklyr` R package](https://github.com/mlverse/pysparklyr/blob/532d4d67dd193f6b3ed070838b08765ac36bc207/R/sparklyr-spark-connect.R#L188)

This pattern is particularly helpful when end users directly invoke functions from a partner platform, such as Posit Workbench. In fact, Posit Workbench now [automatically sets `SPARK_CONNECT_USER_AGENT`](https://github.com/rstudio/rstudio/blob/d9a61920a87d72846f82f7e45fa5a6f1ff75d33c/docs/news/index.qmd#L70).

It would be great if this SQL connector also honored `SPARK_CONNECT_USER_AGENT` when set and submitted it as the [User Agent](https://github.com/databricks/databricks-sql-python/blob/62eb1d407ab03fc2c57a6626bec2173dbdd8bbb3/src/databricks/sql/__init__.py#L33) for a given connection

**Comment by susodapop** [comment]
We won't implement this in databricks-sql-connector because this connector never interacts with spark directly - it's strictly a driver for connecting to databricks sql via Thrift. The user agent in our codebase is hard-coded to `PyDatabricksSqlConnector`.

Users _can_ append to this user agent string by passing as shown in [this example](https://github.com/databricks/databricks-sql-python/blob/main/examples/set_user_agent.py). But this is a separate behaviour from how pyspark uses `SPARK_CONNECT_USER_AGENT` and it really shouldn't be affected by `SPARK_`-prefixed environment variables.
