### ISSUE TITLE
Insert performance is woeful! 😢 

### ISSUE THREAD

**Issue by dhirschfeld** [databricks/databricks-sql-python#365]
When inserting records into a DeltaTable in Unity Catalog it takes about 2s to insert a single record!?!

The insert time appears to scale linearly with the number of records inserted so 100 records would take ~200s

Needless to say, that's completely unusable. I need to insert thousands or tens-of-thousands of records at a time.

----

***xref:***
  - https://github.com/databricks/databricks-sql-python/issues/363

**Comment by mroy-seedbox** [comment]
Data Engineering 101: insert in batches.

**Comment by dhirschfeld** [comment]
The linear scaling with the number of records is unsurprising as `executemany` appears to be implemented as a Python loop!
https://github.com/databricks/databricks-sql-python/blob/main/src/databricks/sql/client.py#L790-L803

**Comment by dhirschfeld** [comment]
> Data Engineering 101: insert in batches.
> 
> This is not a transactional database. Look up the difference between OLTP & OLAP.

That's beside the point. Taking 1 hour to insert a couple of thousand records isn't fit for purpose

**Comment by dhirschfeld** [comment]
I can use `delta-rs` to do the same insert to a DeltaTable in milliseconds

**Comment by mroy-seedbox** [comment]
You need to use dataframes.

**Comment by dhirschfeld** [comment]
> You need to use dataframes.

?

You mean use spark to insert rather than using this library?

**Comment by dhirschfeld** [comment]
If I instead use `pyodbc` with the Simba driver I observer the same 2s per record but when I enable `fast_executemany` with `pyodbc` it takes 2s for the first record, but the rest barely take any more time:
```
Time taken to insert 10 records equals 3.593303 seconds!
Time taken to insert 100 records equals 2.447184 seconds!
Time taken to insert 1000 records equals 3.411159 seconds!
Time taken to insert 10000 records equals 6.527028 seconds!
Time taken to insert 100000 records equals 50.258246 seconds!
Time taken to insert 100000 records equals 46.566044 seconds!
```

...so clearly, there is more that *this* library could be doing to improve the insert performance.

**Comment by dhirschfeld** [comment]
> > You need to use dataframes.
> 
> 
> You mean use spark to insert rather than using this library?

I'm executing externally from Databricks but wanting to push data in, so I don't have a local spark cluster. Googling around a bit, it appears you can connect with the [`databricks-connect`](https://docs.databricks.com/en/dev-tools/databricks-connect/python/index.html) packge.

Nevertheless, I think the insert performance from this library should be as fast as it can be, and given that `pyodbc` is much faster, it shows that it can be done.

**Comment by susodapop** [comment]
I wrote about this a little bit [before](https://github.com/databricks/databricks-sql-python/issues/239#issuecomment-1745520552). But I'll go into it in more detail here.

Consider the following two SQL scripts. Each of which will insert three records into a table. The first one does so by using three `INSERT` statements:

```sql
-- Figure 1
INSERT INTO table field1, field2, field3 VALUES (1,2,3):
INSERT INTO table field1, field2, field3 VALUES (3,4,5):
INSERT INTO table field1, field2, field3 VALUES (6,7,8):
```

The second one uses SQL's batch syntax to do it all in one statement:

```sql
-- Figure 2
INSERT INTO table field1, field2, field3 ((1,2,3),(4,5,6),(7,8,9));
```

With some SQL know-how, you as a human being can easily take the query in `Figure 1` and re-write it into the form shown in `Figure 2`. This is a process known as "merging". But `databricks-sql-connector` cannot merge SQL queries. Because it's a low-level driver with a thin dependency tree. Merging requires a sql parser and this connector doesn't have one.

This was a deliberate decision. This connector has one job and it does it well: it sends your queries and parameters to the server and gives you back whatever the statement returned. 

There are other, better tools for automatically writing SQL queries. Like SQLAlchemy, which the connector has hooks to support. If you want to dynamically write batch-style insert statements, you can use SQLAlchemy or the `pandas.Dataframe.to_sql(method="multi")` function (which also uses SQLAlchemy under the hood).

So how do other DBAPI drivers like `psycopg2` implement their `fast_executemany()` methods? They don't have sql parsers either. Why can't `databricks-sql-connector` do what they do?

Here's the secret to `psycopg2`: it's not merging parameters in the driver! The postgres server has an RPC available where a driver can pass a single execute statement with a batch of parameters and the _server will merge them together_ before executing. Which makes sense because the server doesn't just have **a** sql parser. It has **the** sql parser that matters!

That's how their rudimentary driver achieves such stellar performance. But as of my most recent understanding, this approach isn't possible for Databricks because Spark SQL doesn't support merging parameters on the server-side.  

The Databricks ODBC driver, from what I recall, actually does rewrite SQL queries in the fashion described above.

Broadly speaking, `databricks-sql-connector` wasn't written to be an efficient ingestion tool. But it has been moving in that direction. With the release of Databricks Volumes it's possible to upload large CSV files to Databricks directly using this connector. 

Until Databricks compute supports merging parameters on the back-end, though, there isn't a way to make `executemany()` any more efficient.

I don't work for Databricks, but I hope this helps.

**Comment by susodapop** [comment]
PS in case you're curious:

If you want to see what the ODBC driver is actually doing when you send a lot of records, check the Query History in Databricks SQL's web UI. There you can see the exact SQL that it submitted to the cluster. If you see a transformed query, you can know for certain that the ODBC driver merged/rewrote it. 

I never worked on the ODBC connector. But I have a suspicion that it may actually just be emitting a bunch of non-batch INSERTs, but doing so in parallel using threads. Just a hunch, though.

**Comment by dhirschfeld** [comment]
Thanks for the explanations @susodapop. I think my workaround will probably be to use volumes.

Since this requires support from Databricks on the back-end I'll close this issue here as answered...
