### ISSUE TITLE
GetOperationStatus fails without knowing the reason

### ISSUE THREAD

**Issue by FnayouSeif** [databricks/databricks-sql-python#58]
I have a long running query (Avg of 30 minutes) that sometimes fails (random failures) and the only traceback I get is this:

```
2022-10-24 12:36:21,674 - [INFO] - databricks.sql.thrift_backend - MainThread - Error during request to server: {"method": "GetOperationStatus", "session-id": null, "query-id": "b'i\\xfbv\\xa6\\xed+J\\x13\\xbc\\x90\\x05\\xafR\\x97\\xbf\\xb4'", "http-code": 503, "error-message": "", "original-exception": "", "no-retry-reason": "non-retryable error", "bounded-retry-delay": null, "attempt": "1/30", "elapsed-seconds": "9.045876264572144/900.0"}
``` 

Version: databricks-sql-connector==2.0.4 
Platform: 20.04.1-Ubuntu

**Comment by FnayouSeif** [comment]
@susodapop I updated it in the issue description. Sorry for missing that out

**Comment by susodapop** [comment]
Thank you. Please contact Databricks support so they can open a ticket for this. It appears there may be an issue with the response the Thrift server sends to `databricks-sql-connector` which is not something we should debug on a public forum.

For further background, since version [2.0.3](https://github.com/databricks/databricks-sql-python/releases/tag/v2.0.3), the client will retry GetOperationStatusRequest commands in two situations:
1. If the response is a 429 or 503 HTTP code **and includes a Retry-After header**
2. If the response failed due to an `OSError` (usually a timeout due to network outage)

In your case, the response from the server is a 503 **but does not include a Retry-After header**. We need to understand why server hasn't included that header.

**Comment by susodapop** [comment]
Closing for now. Feel free to reopen if need be in the future.
