### ISSUE TITLE
Source thrift file

### ISSUE THREAD

**Issue by alex-davies** [databricks/databricks-sql-python#85]
Not really an issue, more of question. 

Where is the thrift file that was used to generate the underlaying client? 

I cannot see a .thrift file in the repo and the output does not seem to match the hive thrift file from https://github.com/apache/hive/blob/master/service-rpc/if/TCLIService.thrift. Does databricks have a separate file with extended features?

**Comment by susodapop** [comment]
You are correct that our .thrift file is not present in this repo nor any of our other OSS Thrift-based connectors. Databricks have not chosen to open source it at this time.

Are you blocked by not having this file? How so?

**Comment by susodapop** [comment]
Thanks for that context.

You _can_ use the open source Hive thrift definition to interact with Databricks because the Databricks runtime is backwards compatible with it. But you're right that trying to implement the same features as our OSS connectors that were developed post-fork will be impossible without access to our Thrift contract. I've drawn attention to this with my team, which maintains all our OSS connectors (currently for Python, Node, and Go).

To connect with Databricks from C#, I think your best bet is to connect using our ODBC driver and the C# ODBC tooling.

I'm going to keep your issue closed on this repository since it's not relevant for Python development. But this is an ongoing discussion for us internally and you are welcome to respond here or ping my `@` if you need. Thanks for starting this discussion.

**Comment by rxin** [comment]
@alex-davies we are actually going to release a new REST API with well documented interfaces very soon, and then we will transition all the connectors to that new API. If you can just wait a little bit, we'd love to work with you to get a dotnet version based on that new API.

**Comment by skitscha** [comment]
@susodapop @rxin Are you guys still going to move the connectors over to the rest api? I would also like to make a databricks connector in C#. The ODBC driver is not easy to configure if you are running your application in a container. Would it be possible for you guys to generate the thift files in dotnet and check them into a repo so that I can make a dotnet connector for databricks?

**Comment by jadewang-db** [comment]
https://github.com/apache/arrow-adbc/tree/main/csharp/src/Drivers/Apache/Spark this is an .net ADBC driver against thrift under development.
